import type { Metadata } from "next";
 
import Image from "next/image";

 

import "./globals.css";
import {
  ClerkProvider,
  ClerkLoaded,
  ClerkLoading,
  
} from "@clerk/nextjs";
 
import Header from "@/components/Header";

 
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
 
 

 

export const metadata: Metadata = {
  title: "Good Lifes Utility Bill Payment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ClerkLoading>
            <div className="flex flex-col justify-center items-center h-screen text-2xl">
            <span className="loading loading-spinner text-success text-3xl"></span>         
           <Image
            src="/images/logo.png"
            className="mt-6"
            alt="Good Lifes"
            width={75}
            height={50}
          />  
            </div>
          </ClerkLoading>
          <ClerkLoaded>
            <div className=" w-screen mx-auto">
              <div className="flex flex-col h-screen">
                <div>
                  <Header />
                </div>

                <div className="flex w-screen bg-green-600">
                  <NavBar />
                </div>
                 
                {children}
                 
                <div>
                  <Footer />
                </div>
              </div>
            </div>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}